name: test_net_action
on:
  push:
    branches:
      - main

jobs:
  laravel_action_test_job:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     
      - name: Comando en CMD
        run: dir C:\
